Створення вектора

In [3]:
import numpy as np

vector = np.array([1, 2, 3])

vector

array([1, 2, 3])

In [10]:
vector.shape

(2,)

Додавання/віднімання скаляра (бідь яке число) та вектора

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+2)
print(a-1)

[3 4 5]
[0 1 2]


Додавання та віднімання двох векторів

In [3]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print(a+b)
print(a-b)

[5 7]
[-3 -3]


Скалярний добуток (Dot product) - для отримання інформації стосовно однонаправленості (добток позитивний значить однонаправлені, якщо негативний то різнонаправлені)

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # відбудеться опреація поелементного множення і ми отримаємо новий векто
print(np.dot(a,b)) # отримання скалярного добутку
print(a.dot(b))    # отримання скалярного добутку
print(a @ b)       # отримання скалярного добутку 

[ 4 10 18]
32
32
32


Множення вектора на скаляра (звичайне число)

In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], dtype=float)
b = a * 5 # 5 це скаляр
print(b)

[ 5. 10. 15. 20. 25.]


Створення матриці

In [10]:
import numpy as np

m = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print(m)

[[1 2 3]
 [4 5 6]]


In [11]:
m.shape # розмірність матриці (2 рядки, 3 стовпці)

(2, 3)

Множення матриць

In [17]:
import numpy as np

a = np.array([[1, 2, 3], 
              [0, 1, 2]])

b = np.array([[1, 2],
              [0, 4],
              [-1, 0]])

c = np.dot(a, b) # множення матриць
c = a.dot(b)     # множення матриць
c = a @ b        # множення матриць

print(c)

[[-2 10]
 [-2  4]]


Транспонування матриці (обертання, зміна зі стовпців по колонках, діагональ незмінна)

In [19]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
import numpy as np

a = np.array([
    [1, 2, 3], 
    [4, 5, 6]])

b = a.reshape(3, 2) # зміна на 3 рядки і дві колонки
c = a.reshape(1, -1) # виведення в один рядок
d = a.reshape(-1, 1) # виведення в один стовпець

print(b, b.shape)
print("----------")
print(c, c.shape)
print("----------")
print(d, d.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
----------
[[1 2 3 4 5 6]] (1, 6)
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


In [26]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten() # переводить матрицю у векторний вигляд

print(b)

[1 2 3 4 5 6]


Одинична матриця (квадратна матриця на головній діагоналі стоять 1)

In [33]:
import numpy as np

a = np.eye(4, k=-1, dtype=float)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Обернена матриця

In [36]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)


[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


In [39]:
a_inv @ a

array([[ 1.00000000e+00,  3.33066907e-16, -3.88578059e-16],
       [-1.11022302e-16,  1.00000000e+00,  5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

Інші можливості в NumPy

In [55]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2] 
            ])

In [52]:
a.shape # розмір масиву (кількість рядків та стовпців)

(6, 3)

In [53]:
a.ndim # кількість осей (вимірностей) ndim == len(shape)

2

In [56]:
a.size # кількість елементів у масиві

9

In [57]:
a.dtype # тип елементів у масиві

dtype('int64')

In [58]:
a.itemsize # розмір елемента у байтах

8

Створення масивів (матриці чи вектра) з одиницями

In [59]:
import numpy as np

a = np.ones(5, dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


Створення масивів (матриці чи вектра) з нулями

In [60]:
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


Створення масивів (матриці чи вектра) яка буде послідовністю чисел 

In [1]:
import numpy as np

a = np.arange(5)
b = np.arange(1, 3, 0.5)
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


Як і в range, масиви, згенеровані в цих прикладах, не включають останні елементи 5 та 3
Щоб включити останній елемент визначеної послідовності, можна використовувати метод np.linspace

In [3]:
import numpy as np

a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 2. 3.]


Створення масивів з рандомними даними

In [4]:
import numpy as np

a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print(b)

[0.66324583 0.2180014  0.97960528]
[[0.89824069 0.2043591  0.40844533]
 [0.23476501 0.24802955 0.23600204]
 [0.30739438 0.37754201 0.04574258]]


Індексація

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


In [6]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


Основні типи даних (dtype) NumPy

In [7]:
b = np.zeros((3, 3), dtype="u4")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
import numpy as np

a = np.array([u"\u2211", u"\u220F"], dtype="U")
print(a)  # ['∑' '∏']

['∑' '∏']


Агрегування в NumPy

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.min())  # min — мінімальне значення
print(a.max())  # max — максимальне значення
print(a.sum())  # sum — сума всіх елементів
print(a.mean()) # mean — середнє арифметичне
print(a.prod()) # prod — перемножити всі елементи

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())  # min — мінімальне значення
print(a.max())  # max — максимальне значення
print(a.sum())  # sum — сума всіх елементів
print(a.mean()) # mean — середнє арифметичне
print(a.prod()) # prod — перемножити всі елементи