Створення вектора

In [3]:
import numpy as np

vector = np.array([1, 2, 3])

vector

array([1, 2, 3])

In [10]:
vector.shape

(2,)

Додавання/віднімання скаляра (бідь яке число) та вектора

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+2)
print(a-1)

[3 4 5]
[0 1 2]


Додавання та віднімання двох векторів

In [3]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print(a+b)
print(a-b)

[5 7]
[-3 -3]


Скалярний добуток (Dot product) - для отримання інформації стосовно однонаправленості (добток позитивний значить однонаправлені, якщо негативний то різнонаправлені)

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)  # відбудеться опреація поелементного множення і ми отримаємо новий векто
print(np.dot(a,b)) # отримання скалярного добутку
print(a.dot(b))    # отримання скалярного добутку
print(a @ b)       # отримання скалярного добутку 

[ 4 10 18]
32
32
32


Множення вектора на скаляра (звичайне число)

In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], dtype=float)
b = a * 5 # 5 це скаляр
print(b)

[ 5. 10. 15. 20. 25.]


Створення матриці

In [10]:
import numpy as np

m = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print(m)

[[1 2 3]
 [4 5 6]]


In [11]:
m.shape # розмірність матриці (2 рядки, 3 стовпці)

(2, 3)

Множення матриць

In [17]:
import numpy as np

a = np.array([[1, 2, 3], 
              [0, 1, 2]])

b = np.array([[1, 2],
              [0, 4],
              [-1, 0]])

c = np.dot(a, b) # множення матриць
c = a.dot(b)     # множення матриць
c = a @ b        # множення матриць

print(c)

[[-2 10]
 [-2  4]]


Транспонування матриці (обертання, зміна зі стовпців по колонках, діагональ незмінна)

In [19]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
import numpy as np

a = np.array([
    [1, 2, 3], 
    [4, 5, 6]])

b = a.reshape(3, 2) # зміна на 3 рядки і дві колонки
c = a.reshape(1, -1) # виведення в один рядок
d = a.reshape(-1, 1) # виведення в один стовпець

print(b, b.shape)
print("----------")
print(c, c.shape)
print("----------")
print(d, d.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
----------
[[1 2 3 4 5 6]] (1, 6)
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


In [26]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten() # переводить матрицю у векторний вигляд

print(b)

[1 2 3 4 5 6]


Одинична матриця (квадратна матриця на головній діагоналі стоять 1)

In [33]:
import numpy as np

a = np.eye(4, k=-1, dtype=float)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Обернена матриця

In [36]:
import numpy as np

a = np.array([[ 1, 0, 3],
              [-1,-1, 2],
              [ 4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)


[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


In [39]:
a_inv @ a

array([[ 1.00000000e+00,  3.33066907e-16, -3.88578059e-16],
       [-1.11022302e-16,  1.00000000e+00,  5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])